# 필수 이벤트 섹션
events {
    worker_connections 1024;
}

# 웹 설정
http {
	include       mime.types;
    default_type  application/octet-stream;
    
     
    # upstream: 백엔드 서버 그룹
    upstream was-cluster {
    		#ip_hash; # 같은 pc에서는 서버 1곳으로 이동
        server 127.0.0.1:8080;
        server 127.0.0.1:8090;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
        	# 상대경로로 수정
            root   "../src/main/webapp";
            index  index.html login.html;
	        try_files $uri $uri/ @proxy;
        }

        location /sample-project/ {
		    proxy_pass http://was-cluster;
		    proxy_set_header Host $host;
		    proxy_cookie_path /sample-project /; # 쿠키를 루트(/)에서 쓸 수 있게 함
		}
	        
	       
	    

        # 톰캣으로 배달하는 핵심 통로, proxy는 url 숨기기
        location @proxy {
            proxy_pass http://was-cluster;
    
		    # 쿠키 경로 변환 추가
		    proxy_cookie_path / /;
		    proxy_cookie_domain localhost localhost;
		    
		    proxy_set_header Cookie $http_cookie;
		    proxy_redirect default;
		    proxy_set_header Host $host;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 개별 기능 매핑
        #location /login { 
        #    proxy_pass http://was-cluster/sample-project/login;
	    #    proxy_set_header Host $host;
	    #    proxy_set_header X-Nginx-Port $server_port;
	    #    proxy_cookie_path /sample-project /;
        #}
    }
}